from src.gradio_ui import create_ui

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

def main():
    """The main function to launch the Gradio application."""
    
    print("Launching Gradio UI...")
    app = create_ui()
    
    # Launch the app
    app.launch(server_name="0.0.0.0", server_port=7860)
    print("Gradio UI is running.")

if __name__ == "__main__":
    main()
